services:
  vault:
    image: hashicorp/vault:1.20
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=vui-sandbox-token
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vol/vault/file:/vault/file

  ldap:
    image: osixia/openldap:1.5.0
    ports:
      - "127.0.0.1:8389:389"
    environment:
      - LDAP_ORGANISATION="Vui Sandbox"
      - LDAP_DOMAIN=sandbox.vui
      - LDAP_ADMIN_PASSWORD=vui-sandbox-admin-password
      - LDAP_TLS=false
    command: ["--copy-service"]
    volumes:
      - ./files/ldap_bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sts,iam
    volumes:
      - "./vol/localstack:/var/lib/localstack"

  init_vault_ldap:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_ldap:/status/vault_ldap
    depends_on:
      - vault
      - ldap
    entrypoint: ["/vui/init_vault_ldap.sh"]
    restart: "on-failure:10"

  init_vault_aws:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_aws:/status/vault_aws
    depends_on:
      - vault
      - localstack
    entrypoint: ["/vui/init_vault_aws.sh"]
    restart: "on-failure:10"

  init_localstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_localstack:/status/localstack
    depends_on:
      - localstack
    entrypoint: ["/vui/init_localstack.sh"]
    restart: "on-failure:10"
