services:
  vault:
    image: hashicorp/vault:1.20
    ports:
      - "127.0.0.1:8200:8200"
      - "127.0.0.1:8208:8208"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=vui-sandbox-token
      - VAULT_LOG_LEVEL=debug
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vol/vault/file:/vault/file
      - ./vol/vault/certs:/vault/certs:rw
      - ./files/vault_config.hcl:/vault/config/config.hcl
      - ./files/vault.crt:/vault/certs/server.crt
      - ./files/vault.key:/vault/certs/server.key
    extra_hosts:
      - "kubernetes.default.svc.cluster.local:host-gateway"

  ldap:
    image: osixia/openldap:1.5.0
    ports:
      - "127.0.0.1:8389:389"
    environment:
      - LDAP_ORGANISATION="Vui Sandbox"
      - LDAP_DOMAIN=sandbox.vui
      - LDAP_ADMIN_PASSWORD=vui-sandbox-admin-password
      - LDAP_TLS=false
    command: ["--copy-service"]
    volumes:
      - ./files/ldap_bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  localstack:
    image: localstack/localstack:4.9.2
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sts,iam,secretsmanager,ssm
    volumes:
      - "./vol/localstack:/var/lib/localstack"

  oidc:
    # http://localhost:8080/realms/vui-sandbox-realm/protocol/openid-connect/auth?client_id=vui-sandbox-oidc-client-id&response_type=code&redirect_uri=http://localhost:8250/auth/callback
    image: quay.io/keycloak/keycloak:26.4
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - "./files/oidc_realm_config.json:/opt/keycloak/data/import/realm-config.json"
    command: ["start-dev", "--import-realm"]

  init_vault_ldap:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_ldap:/status/vault_ldap
    depends_on:
      - vault
      - ldap
    entrypoint: ["/vui/init_vault_ldap.sh"]
    restart: "on-failure"

  init_vault_aws:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_aws:/status/vault_aws
    depends_on:
      - vault
      - localstack
    entrypoint: ["/vui/init_vault_aws.sh"]
    restart: "on-failure"

  init_vault_k8s:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_k8s:/status/vault_k8s
      - ./vol/kind/kube:/root/.kube
      - ./vol/kind/pki:/etc/kubernetes/pki
    depends_on:
      - vault
    entrypoint: ["/vui/init_vault_k8s.sh"]
    restart: "on-failure"
    extra_hosts:
      - "kubernetes.default.svc.cluster.local:host-gateway"

  init_localstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_localstack:/status/localstack
    depends_on:
      - localstack
    entrypoint: ["/vui/init_localstack.sh"]
    restart: "on-failure"

  init_vault_oidc:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_oidc:/status/vault_oidc
    depends_on:
      - vault
      - oidc
    entrypoint: ["/vui/init_vault_oidc.sh"]
    restart: "on-failure"

  init_vault_jwt:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_jwt:/status/vault_jwt
    depends_on:
      - vault
      - oidc
    entrypoint: ["/vui/init_vault_jwt.sh"]
    restart: "on-failure"

  init_vault_userpass:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    volumes:
      - ./vol/init_vault_userpass:/status/vault_userpass
    depends_on:
      - vault
    entrypoint: ["/vui/init_vault_userpass.sh"]
    restart: "on-failure"

  init_vault_cert:
    build:
      context: .
      dockerfile: Dockerfile
    image: vui/sandbox:init
    pull_policy: never
    environment:
      - VAULT_ADDR=https://vault:8208
      - VAULT_CACERT=/vault/certs/server.crt
    volumes:
      - ./vol/init_vault_cert:/status/vault_cert
      - ./files/vault.crt:/vault/certs/server.crt
      - ./vol/certs:/certs
    depends_on:
      - vault
    entrypoint: ["/vui/init_vault_cert.sh"]
    restart: "on-failure"
