kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: vui-sandbox
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./vol/kind/pki
    containerPath: /etc/kubernetes/pki
