app:
  log_level: "info"
  log_file: "vui.log"

ui:
  theme: "default"
  show_hidden_secrets: false

profiles:
  vault-token:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "token"
    namespace: ""
    auth_config:
      token: "${VAULT_TOKEN}"

  vault-ldap:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "ldap"
    namespace: ""
    auth_config:
      username: "${LDAP_USERNAME}"
      password: "${LDAP_PASSWORD}"

  vault-aws:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "aws"
    namespace: ""
    auth_config:
      aws_role: "vui-iam-role"
      aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
      aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
      aws_session_token: "${AWS_SESSION_TOKEN}"

  vault-k8s:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "kubernetes"
    namespace: ""
    auth_config:
      k8s_role: "vui-k8s-role"
      k8s_service_account: "vui-sandbox-app-sa"
      k8s_audience: "vault"
      k8s_ttl: 3600

  vault-oidc:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "oidc"
    namespace: ""
    auth_config:
      oidc_role: "vui-oidc-role"

  vault-jwt:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "jwt"
    namespace: ""
    auth_config:
      jwt_role: "vui-jwt-role"
      jwt: "${JWT}"

  vault-userpass:
    engine: "vault"
    address: "http://localhost:8200"
    auth_method: "userpass"
    namespace: ""
    auth_config:
      username: "${USERPASS_USERNAME}"
      password: "${USERPASS_PASSWORD}"

  vault-cert:
    engine: "vault"
    address: "https://localhost:8208"
    cert_path: "./sandbox/files/vault.crt"
    auth_method: "cert"
    namespace: ""
    auth_config:
      cert_name: "vui-sandbox-user"
      cert_crt_path: "./sandbox/vol/certs/client.crt"
      cert_key_path: "./sandbox/vol/certs/client.key"

  vault-azure-todo:
    engine: "vault"
    address: "http://localhost:8201"
    auth_method: "azure"
    namespace: ""
    auth_config:
      azure_role: "vui-azure-role"
      azure_resource: "TODO"

  aws-secretsmanager:
    engine: "aws/secretsmanager"
    address: "http://localhost:4566"
    auth_method: "aws"
    namespace: ""
    auth_config:
      aws_region: "us-east-1"
      aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
      aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
      aws_session_token: "${AWS_SESSION_TOKEN}"
